version: '3.8'

services:
  app:
    image: test/mytest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mytest
    env_file:
      - .env
    expose:
     - "80"
    restart: always

networks:
  default:
    external: true
    name: webproxy
