version: '3.8'

services:
  app:
    image: funklid/scan-app
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: scan-app
    env_file:
      - .env
    expose:
     - "80"
    restart: always

volumes:
  mysql-data-SCAN-app:

networks:
  default:
    external: true
    name: webproxy
